apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: kabanero-trigger-template
spec:
  params:
  - name: git-repo-url
    description: URL for the git repository
  - name: git-revision
    description: Git commit identifier for the trigger
  - name: git-branch
    description: Git branch
  - name: ibmcloud-api
    description: the ibmcloud api URL
  - name: ibmcloud-api-key
    description: API key for the account
  - name: cluster-name
    description: Name of the ROKS cluster to connect
  - name: openshift-project-name
    description: OpenShift project name
  - name: icr-url
    description: URL for IBM Container Registry
  - name: icr-namespace
    description: Namespace on IBM Container Registry
  - name: icr-repository
    description: Repository name on IBM Container Registry  
  - name: docker-imagetag
    description: Image tag for the image

  resourcetemplates:

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pipeline-account
    secrets:

  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: kabanero-pipelines-build-push-pipelinerun
    spec:
      serviceAccountName: pipeline-account
      pipelineRef:
        name: kabanero-pipelines-build-push-pipeline
      params:
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: git-branch
        value: $(params.git-branch)
      - name: git-revision
        value: $(params.git-revision)
      - name: ibmcloud-api
        value: $(params.ibmcloud-api)
      - name: ibmcloud-api-key
        value: $(params.ibmcloud-api-key)
      - name: cluster-name
        value: $(params.cluster-name)
      - name: openshift-project-name
        value: $(params.openshift-project-name)
      - name: icr-url
        value: $(params.icr-url)
      - name: icr-namespace
        value: $(params.icr-namespace)
      - name: icr-repository
        value: $(params.icr-repository)
      - name: docker-imagetag
        value: $(params.docker-imagetag)  